/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Seller;

import Interface.AdministrativeRole.ManageUserAccountJPanel;
import Business.AuctionPlatform.AuctionPlatform;
import Business.EcoSystem;
import Business.Market.Market;
import Business.Organization.Organization;
import Business.Organization.SellerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chess
 */
public class SellerWorkArea extends javax.swing.JPanel {

    /** Creates new form SellerWorkArea */
    JPanel userProcessContainer;
    UserAccount userAccount;
    AuctionPlatform auctionplatform;
    Market market;
    EcoSystem system;
    
    public SellerWorkArea(JPanel userProcessContainer,UserAccount userAccount,SellerOrganization organization,AuctionPlatform auctionplatform,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.auctionplatform = auctionplatform;
        this.system = system;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPlaceAnAuction = new javax.swing.JButton();
        btnNowBidding = new javax.swing.JButton();
        btnBiddingHistory = new javax.swing.JButton();
        btnBiddingTime = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Work Area -Seller");

        btnPlaceAnAuction.setText("PlaceAnAuction");
        btnPlaceAnAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceAnAuctionActionPerformed(evt);
            }
        });

        btnNowBidding.setText("NowBidding");
        btnNowBidding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNowBiddingActionPerformed(evt);
            }
        });

        btnBiddingHistory.setText("BiddingHistory");
        btnBiddingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiddingHistoryActionPerformed(evt);
            }
        });

        btnBiddingTime.setText("BiddingTime");
        btnBiddingTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiddingTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNowBidding, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBiddingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBiddingTime, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaceAnAuction, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(btnPlaceAnAuction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNowBidding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBiddingHistory)
                .addGap(18, 18, 18)
                .addComponent(btnBiddingTime)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceAnAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceAnAuctionActionPerformed
        // TODO add your handling code here:
        PlaceAnAuction place = new PlaceAnAuction(userProcessContainer, system);
        userProcessContainer.add("PlaceAnAuction", place);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPlaceAnAuctionActionPerformed

    private void btnNowBiddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNowBiddingActionPerformed
        // TODO add your handling code here:
        NowBidding nowBidding = new NowBidding(userProcessContainer, system);
        userProcessContainer.add("NowBidding", nowBidding);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNowBiddingActionPerformed

    private void btnBiddingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiddingHistoryActionPerformed
        // TODO add your handling code here:
        BiddingHistory history = new BiddingHistory(userProcessContainer,system);
        userProcessContainer.add("BiddingHistory", history);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBiddingHistoryActionPerformed

    private void btnBiddingTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiddingTimeActionPerformed
        // TODO add your handling code here
        BiddingTime time = new BiddingTime(userProcessContainer,system);
        userProcessContainer.add("BiddingTime", time);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBiddingTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiddingHistory;
    private javax.swing.JButton btnBiddingTime;
    private javax.swing.JButton btnNowBidding;
    private javax.swing.JButton btnPlaceAnAuction;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
